### PR TITLE
Extract parser into separate module

### PR DESCRIPTION
**Pull request by jnicklas**
Hejsan! I've found this project, and it's very very similar to something that I've been playing around with, only much further along than how far I got. Thank you very much for putting this together, it must have taken an enormous amount of effort. I would like to help out a bit.

I feel kind of bad about this pull request, since I'm making massive changes to the project structure as my first contribution, maybe you don't even want contributions for this project, that'd be totally okay. Maybe this is just too massive of a change, that's okay too. I totally won't mind if you just close this down.

When I was looking through the project I had some thoughts on how to improve the organization and architecture of it, rather than just come in and complain I thought I'd try to actually do something about it.

Let me try and motivate why I think this is a good idea:

I think it's good practice in writing a compiler to separate the different stages of compilation, I'm not a computer scientist, but from what I know this is a common practice in compiler design. In terms of a Sass compiler, I think the stages should be:

- parse: Parse Sass code into Sass AST
- compile: Transform Sass AST into a CSS AST
- trans: Walk the CSS AST and print it out

This is made somewhat more complicated by the fact that the nesting applied in the original Sass code needs to be preserved in some formatters, but I think this is solvable. One alternative design is to transform the CSS AST into a CST first, before trans, but I think this is unnecessary.

This library already somewhat applies this general design, but what it does not yet do is apply a clear distinction between these stages. Currently code for parsing, compiling and trans is somewhat intermixed. I think this makes the library much harder to work with.

For example, my original goal was to help out by adding support for selectors with interpolations, but this presented a problem: currently selectors are transformed into CSS via a `fmt::Display` implementation. This design doesn't hold for interpolations, since they need to be aware of the scope and other such stuff. Obviously this problem is fixable, but it presents a clear motivation for this design change, in that the interpolation really should have been applied before we even get to the printing part. It makes the `trans` stage much more complicated than it needs to be.

Instead of implementing how every kind of sass expression can be printed, we first implement the transformation to CSS AST. The printing then becomes much easier, since the CSS AST is much smaller than the Sass AST. This is actually somewhat similar to what's happening inside rustc with MIR if you've been following this discussion.

This PR really doesn't do anything other than take all the parsing related code and stuff it into a module. There are more refactorings that could be done to improve this even further, but I'd figure I'd start out with the most minmal possible change, which still ended up huge.

The only change in functionality is that some fields and methods which were previously private have been made `pub`. I did this so that I wouldn't impact the code too much other than moving things around, maybe we can tighten up privacy later again.

### CODE REVIEW

**Comment by kaj** [comment]
Some source files was getting rather long, so I was thinking about splitting them up in some way, and separating the parser functions from other parts was one way I considered (even though it is kind of opposite (or at least orthogonal) the splitting I've already done (mainly separating value content from everything else).

So at least I won't ditch this PR from the start.  :-)  But be warned that I will need some time to consider a change this big (even after Travis approves it).

**Comment by jnicklas** [comment]
I totally understand!

Travis is happy now at least, just had some problems with rustfmt.

**Comment by jnicklas** [comment]
Just realized that the value tests were not running, so I had to do some clean up there. I moved the tests which use `check_expr` into an inline module in the parser, because they seem unit-testy to me in that they *just* test the parser. I moved the tests which use `check_eval` into `./tests` since they seem more integration test like to me.

I dislike having to expose `value_expression` as `pub`, I'll  try to find a nicer interface for this that makes sense to expose publicly.

**Comment by kaj** [comment]
> Just realized that the value tests were not running,

Are you a mind reader?  I was just thinking that, but hadn't verified it enough to write a comment about it yet ...  :-)

> I dislike having to expose value_expression as pub, I'll try to find a nicer interface for this that makes sense to expose publicly.

I guess we could have a method that is both `#[cfg(test)]` and `pub`, which takes a string, parses it as a value, evaluates the value (maybe with some specified variable scope), formats the resulting value and returns the result as a `String` (or a `Vec<u8>`).

Another way is what is done in `test/interpolate_00_concatenation.rs`.  It simply wraps the value in a minimal style sheet, sassifies that and tests the result.  But I think that is uglier, and was actually about to move those tests in together with the tests under `src/value` and use `check_eval` in them.

**Comment by jnicklas** [comment]
I agree that just compiling the value is much nicer for these tests, and better than wrapping them in a minimal stylesheet.

With the changes I made to the code organization in this PR it feels to me like they fit better in `./tests` as integration tests, rather than under `./src` as unit tests, since they exercise the entire compiler chain.

I pushed another commit which adds a more sensible interface for compiling a single value and uses that interface from the tests. I think this kind of method makes sense as a public interface since it could be useable from a repl or CLI or something like that for playing around with value expressions.

**Comment by jnicklas** [comment]
🎉

**Pull request merged**
